# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57d52f636f61c2af24c4cf99a8090713a758bf7c4949259cfac41d1ab72e16a77918b217488f831584fafebc1cd4603308905204be4a6233c5aa538557c5a630

test:
  secret_key_base: 7c42f6e7f285775692aff3d35360212d2fca9379089a114342e7d31c5fd20a8f6cd1d7ec3adfcc830f24696b36b83ac894f7113a8b0d76a2772cbbf5f00f0694

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
